Drop support of cucumber <7
reportportal/agent-js-cucumber pull request #159
Opened 2024-01-31 07:08 UTC by AliakseiLiasnitski

2024-02-05 16:04 UTC, AmsterGet requested changes
Please also remove `deprecated` api mention from `jest.config.js`

![image](https://github.com/reportportal/agent-js-cucumber/assets/31861805/6cca1c16-2401-4556-85d4-d9ef88917cb7)

2024-02-05 16:04 UTC, AmsterGet commented on tests/cucumber-reportportal-formatter.spec.js
> +    it('sendLog should be called with pending message', () => {
I would suggest to add a 'in case of corresponding status received' at the end of the test name.
Could be added to 2 other similar tests.

2024-02-05 16:04 UTC, AmsterGet commented on tests/cucumber-reportportal-formatter.spec.js
> +      it('finishTestItem should be called with faild status, clean storage', () => {
```suggestion
      it('finishTestItem should be called with failed status, clean storage', () => {
```

2024-02-05 16:04 UTC, AmsterGet commented on tests/cucumber-reportportal-formatter.spec.js
> +    describe('FAILED status', () => {
```suggestion
    describe('finishsed with failed status', () => {
```
I suggest to keep the same letter case for the same stuff (like statuses in this case).

2024-02-06 08:27 UTC, AliakseiLiasnitski commented on tests/cucumber-reportportal-formatter.spec.js
> +    it('finishTestItem should be called with NOT_ISSUE type', () => {
I deleted this case because it was a duplicate

2024-02-06 10:41 UTC, AmsterGet approved these changes

2024-02-06 10:42 UTC, merged